### ISSUE TITLE
Unable turning on the mod

### ISSUE THREAD

**Issue by Ygarr** [minetest-mods/flowerpot#16]
It make break(or conflicts) a lot of other mods(10+) like ethereal and not only regarding to nature.
Please update functionality to make it compatible again

**Comment by SmallJoker** [comment]
Please provide reproduction steps and optimally a critical dependency path that likely is the reason for this issue.

**Comment by Ygarr** [comment]
After passing time and updates it seems the bug not reproducing for now
![screenshot_20230105_015613](https://user-images.githubusercontent.com/14309871/210674400-50dbd5ce-8d75-4d33-bb3b-2e3bd9320560.png)
