### ISSUE TITLE
MTG 5.0 plants

### ISSUE THREAD

**Issue by proailurus** [minetest-mods/flowerpot#3]
I've tried adding the following new plants from MTG 5.0 to init.lua:

blueberry_bush_sapling
chrysanthemum_green
emergent_jungle_sapling
fern
large_cactus_seedling
pine_bush_sapling
tulip_black

They all work except 'chrysanthemum_green' and 'fern'. Any idea why that could be?

**Comment by Panquesito7** [comment]
> They all work except `chrysanthemum_green` and `fern`. Any idea why that could be?

What is the issue you get? Does it crash, or does it not let you to place it?

**Comment by sofar** [comment]
Should be fixed now, thanks to @Panquesito7 's PR.
