### ISSUE TITLE
Blueberry bush does not fit in pot

### ISSUE THREAD

**Issue by mazes-80** [minetest-mods/flowerpot#6]
Sorry not opening a PR, but I don't like forking for a single line change

[blueberry.patch.txt](https://github.com/minetest-mods/flowerpot/files/4077683/blueberry.patch.txt)

Github weird attach policy does not let me attach patch file type, so I just added a .txt ...

**Comment by tuedel** [comment]
Same for `default:pine_bush_sapling` :wink:

**Comment by mazes-80** [comment]
So slight change to the previous patch:
[flowerpot-bushes.patch.txt](https://github.com/minetest-mods/flowerpot/files/4107382/flowerpot-bushes.patch.txt)

**Comment by SmallJoker** [comment]
8802188
